sonar.projectKey=nandyla_siva-ROBOSHOP-JENKINS123
sonar.projectName=nandyla_siva-ROBOSHOP-JENKINS123
sonar.sources=.
sonar.exclusions=Jenkinsfile, **/db/**, **/node_modules/** # no need to scan these files